version: 0.2
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $APPLICATION_NAME .
      - docker tag $APPLICATION_NAME:latest $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION  > imageDetail.json
      - printf '[{"name":"%s","imageUri":"%s"}]' $APPLICATION_NAME $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - sed -i 's/<APPLICATION_NAME>/'$IMAGE_REPO_NAME'/g' appspec.yml taskdef.json
      - sed -i 's/<AWS_ACCOUNT_ID>/'$AWS_ACCOUNT_ID'/g' taskdef.json
artifacts:
  files: 
    - imageDetail.json
    - appspec.yml
    - taskdef.json